# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x28da2f67980
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.6778733  0.99913776 0.32340905]
 [0.80102263 0.63409661 0.5830536 ]
 [0.77240095 0.51626272 0.66817416]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.6778733  0.99913776 0.32340905]
 [0.80102263 0.63409661 0.5830536 ]
 [0.77240095 0.51626272 0.66817416]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 

arr1_1 = np.random.rand(3, 4)
print(arr1_1)
print("Тип:", arr1_1.dtype)
print("Розмірність:", arr1_1.shape)
print("Довжина:", len(arr1_1))
print("К-сть вимірів:", arr1_1.ndim)
print("К-сть елементів:", arr1_1.size)
print("Байтів:", arr1_1.itemsize)
print("Память:", arr1_1.nbytes)

[[0.58786697 0.2191463  0.92498632 0.48522715]
 [0.18321081 0.19913658 0.34208414 0.05511811]
 [0.60474467 0.74612445 0.96846842 0.16065925]]
Тип: float64
Розмірність: (3, 4)
Довжина: 3
К-сть вимірів: 2
К-сть елементів: 12
Байтів: 8
Память: 96


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів

arr1_2 = np.array(['a', 'b', 'c', 'd', 'e'])
print(arr1_2)

['a' 'b' 'c' 'd' 'e']


In [ ]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою

arr1_3 = np.random.rand(3, 4)
print(arr1_3)

## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [14]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [16]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [17]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [18]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'


arr2_1 = np.full((3,1,3), False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [19]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3,3)
arr2_2 = arr2_2.astype("int64")
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10,21,2).reshape(2,3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [21]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [22]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[35 43 15 39]
 [44 44 17 49]
 [30 18 34 16]
 [39 17 45 23]]


In [23]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

49


In [24]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[39 17 45 23]


In [25]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[35 43 15 39]
 [44 44 17 49]]


In [26]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[43 15]
 [44 17]
 [18 34]
 [17 45]]


In [27]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[35 43 15 39]
 [30 18 34 16]]


In [28]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[35 43 39 44 44 49 30 34 39 45 23]


### ЗАВДАННЯ 3

In [29]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4, 5))
print(arr3_1)

[[90 75 46 21 69]
 [97 49 46 55 76]
 [36 91 27 45 12]
 [14 11 93 30 85]]


In [30]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr[1, 2]
print(el3_2)

17


In [31]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[97 49 46 55 76]


In [32]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2:3]
print(vect3_4)

[[46]
 [46]
 [27]
 [93]]


In [33]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[49 46]
 [91 27]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [34]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [36]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.7367692  0.11752566 0.02847463 0.59980925 0.65601964]
 [0.30356288 0.20694413 0.85891407 0.97617767 0.2239651 ]
 [0.17335844 0.92412061 0.54828993 0.95470053 0.72215353]
 [0.63926793 0.57453914 0.42544678 0.93321628 0.31335122]
 [0.98867712 0.3043753  0.81898813 0.74609724 0.29792583]]
...
[0.7367692  0.20694413 0.54828993 0.93321628 0.29792583]


In [37]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.7367692  0.30356288 0.17335844 0.63926793 0.98867712]
 [0.11752566 0.20694413 0.92412061 0.57453914 0.3043753 ]
 [0.02847463 0.85891407 0.54828993 0.42544678 0.81898813]
 [0.59980925 0.97617767 0.95470053 0.93321628 0.74609724]
 [0.65601964 0.2239651  0.72215353 0.31335122 0.29792583]]


In [38]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.16486067462639684


In [39]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 0.12888415 -0.83437541 -0.4675332   0.5507125   0.89748767]
 [-1.05607685 -1.37362353  0.78597974  0.94265687  0.46142412]
 [-0.58957604  0.38329827  0.61175891 -1.69597996  1.31100269]
 [ 0.42615037  1.22772095 -0.81188895  1.62600614 -1.6035273 ]
 [ 1.20474637  0.04400089  1.10004353 -2.20044552  0.31860287]]


### ЗАВАДАННЯ 4

In [40]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 200, (6, 6))
print(mat4_1)

[[182 194 136 144 131 143]
 [141 137 134 135 147 163]
 [101 151 120 184 150 146]
 [103 143 167 134 145 175]
 [135 183 192 171 190 108]
 [135 119 187 124 161 194]]


In [41]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[182 137 120 134 190 194]


In [42]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[182 141 101 103 135 135]
 [194 137 151 143 183 119]
 [136 134 120 167 192 187]
 [144 135 184 134 171 124]
 [131 147 150 145 190 161]
 [143 163 146 175 108 194]]


In [43]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 0.0110559  -0.01040988  0.00534887 -0.02567822 -0.00173733  0.02070207]
 [-0.00252203  0.02356657 -0.01746702  0.03252374  0.00264946 -0.03560986]
 [ 0.01304286 -0.04799165  0.00983151 -0.00979228  0.00115846  0.03149818]
 [ 0.01412066 -0.04967839  0.0331444  -0.02956024 -0.00551993  0.03612595]
 [-0.02942568  0.07129044 -0.02515313  0.01608463  0.01251035 -0.04075278]
 [-0.00332406  0.01163768 -0.00279518  0.01290327 -0.00838697 -0.00704013]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [46]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [47]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [48]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [49]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [50]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [51]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [52]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [53]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [54]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\Zhytnyk.Vadym\AppData\Local\Temp\ipykernel_4004\3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [55]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [56]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [57]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [58]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [59]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [60]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[5 6 1 2 9]
[5 6 1 2 9]
2807378037136 2807378037136
[5 6 1 2 9]
2807378037136 2807378044432


In [61]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [62]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(1, 20, (4,3))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[ 1  6  8]
 [13  2 11]
 [14 18 11]
 [16  2  2]]
[15 26 43 20]


In [63]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)


15


In [65]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[101 106 108]
 [113 102 111]
 [114 118 111]
 [116 102 102]]


In [66]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
diag = np.diagonal(mat5_3).reshape(3, 1)
mat5_4 = np.dot(mat5_1, diag)
print(mat5_4)

[[1601]
 [2738]
 [4471]
 [2042]]


In [67]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print(np.linalg.matrix_rank(mat5_5))

[[ 101  106  108 1601]
 [ 113  102  111 2738]
 [ 114  118  111 4471]
 [ 116  102  102 2042]]
4
